### ISSUE TITLE
Bug on MacOS

### ISSUE THREAD

**Issue by raphaelleroffo** [austromorph/cartogram3#36] opened 2022-02-13 21:55 UTC
Hi there,

I installed the plugin through the QGIS plugin downloader and it keeps crashing, opening 10 new QGIS windows and actually not running the cartogram algorithm. 
I tried downloading directly the latest version using the source code zip, but I get this error:
``` 
Couldn't load plugin '__MACOSX/cartogram3-3.1.2' 
ModuleNotFoundError: No module named '__MACOSX/cartogram3-3' 
```

Wondering if it's just a MacOS issue as I have not found anyone else complaining about this online.

I teach GIS and have been using this plugin last year, was hoping I could keep teaching it to the current and next cohorts!

Thanks

**Comment by christophfink** [comment] 2022-02-15 14:37
Hi Raphaëlle! 

Sorry to hear that the plugin does not work for you (and thanks for the bug report). 

I’ll only have access to a Mac towards the end of the week to try to find out more about the error. In the meantime, could you answer the following few questions that might help me close in on what exactly the problem is?

- How do you try to manually load the plugin? (It seems something related to the way of how MacOS handles zip archives gets into the way)
- Which version of QGIS and MacOS do you use? Which Python version?

Thanks!

**Comment by raphaelleroffo** [comment] 2022-02-18 17:10
Hi Christoph,

Thank you so much for your reply and sorry that my initial description of the bug wasn't more complete!

- I'm on MacOS Monterey 12.1, and use QGIS 3.16 Hannover. I have Python 3.9.8 on my laptop bu the version of Python that QGIS runs on seems top be 3.8.7 (`sys.version_info` returns `major=3, minor=8, micro=7, releaselevel='final', serial=0`).

- As for the plugin:

1. I first tried loading the plugin using the Plugins manager but it kept launching the weird behaviour (does not run, then opens 10 or 12 new QGIS windows)

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/42731033/154727913-3d46b319-c514-4776-84a2-f3714b0caaeb.png">

2. I then tried going on https://plugins.qgis.org/plugins/cartogram3/version/3.0.4/ and using the download button. It did not download as zip so I tried zipping it and loading it using `Install from ZIP`. It raised this error:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/42731033/154728955-9f3cb24d-dad4-44bd-ad90-9b75bb292d44.png">

The plugin (v 3.0.4) still actually gets installed, but in fact it does not run properly.
When I run the cartogram (whichever method I tried to install it with), after it crashes it also doesn't appear in the History so I can't tell you about the error codes unfortunately.


Let me know if I can do any test to help you pinpoint what's happening!

Many thanks,

Raphaëlle

**Comment by christophfink** [comment] 2022-02-21 15:12
I’m fairly certain, that updating both:

- QGIS to the latest LTR or stable version (3.16.16 or 3.22.4), and
- the cartogram plugin to its latest version (3.1.2)

would solve your issues. 

EDIT: I tried with these combinations, and it works for me on a clean MacOS 10.15.7)

**Comment by christophfink** [comment] 2022-02-21 15:13
And the automatic unzipping of Safari is definitely interfering with installing anything downloaded as a zip archive. 
see also https://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download

**Comment by christophfink** [comment] 2022-02-21 15:22
Maybe still as an explanation: 

At some point between September 2019 (cartogram 3.0.4) and summer 2021, the cartogram3 plugin broke on MacOS. I don’t regularly use a Mac anymore, so I did not realise at first. 

When I fixed the plugin in December 2021, I improved its architecture, and used Python language features available only from version 3.9 onward, which is included in QGIS 3.16.12 and newer. This is why older QGIS versions do not update the cartogram plugin, but need to be upgraded themselves, first.

Please let me know whether updating QGIS (and then the cartogram plugin, simply from the plugin manager) resolves the problem!

**Comment by christophfink** [comment] 2022-02-21 15:50
I ran into a different problem on QGIS 3.16 on MacOS and just uploaded a new version of the plugin. It usually takes a few days for the admins there to accept new plugin versions, look out for cartogram3-3.1.3, which should work better.

**Comment by christophfink** [comment] 2022-03-01 17:31
Hi @raphaelleroffo , just wanted to ask whether you managed to make it work?

**Comment by christophfink** [comment] 2022-03-09 11:28
I’ll assume it’s working and close this issue now. Feel free to re-open it.

**Closed as completed by christophfink** 2022-03-09 11:28 UTC
